# Generated by Django 4.2.1 on 2023-06-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_register_ip_register_mac_register_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='register',
            name='mac',
        ),
        migrations.RemoveField(
            model_name='register',
            name='name',
        ),
    ]
