# Generated by Django 4.2.1 on 2023-06-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_register_ip_remove_register_mac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('user_id', models.IntegerField()),
                ('mac', models.CharField(max_length=10)),
                ('ip', models.GenericIPAddressField()),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
