# Generated by Django 4.2.1 on 2023-06-05 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mac',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
