# Generated by Django 4.2.1 on 2023-06-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customuser_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ip',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='mac',
            field=models.CharField(max_length=50),
        ),
    ]
