# Generated by Django 4.2.1 on 2023-06-05 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_session_ip_alter_session_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
