# Generated by Django 4.2.1 on 2023-06-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_state_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
