# Generated by Django 4.2.1 on 2023-06-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state_name',
            new_name='state',
        ),
    ]
