# Generated by Django 4.2.1 on 2023-06-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
    ]
