# Generated by Django 4.2.1 on 2023-06-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_delete_blacklistedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
