# Generated by Django 4.2.3 on 2023-07-05 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_saving_transection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.PositiveIntegerField(default=0)),
                ('address', models.TextField()),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agentuser')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Transection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agentuser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.loan_account')),
            ],
        ),
    ]
