# Generated by Django 4.2.2 on 2023-06-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_organizationmodel_customuser_organization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(default=0)),
                ('space', models.IntegerField(default=1048576)),
            ],
        ),
    ]
