# Generated by Django 4.2.2 on 2023-06-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_spacemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorMobel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=100)),
                ('organization_id', models.IntegerField(default=0)),
            ],
        ),
    ]
