# Generated by Django 4.2.2 on 2023-06-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_monitormobel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='organizationmodel',
            name='username',
        ),
    ]
