# Generated by Django 4.2.2 on 2023-06-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_organizationmodel_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_TypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
