# Generated by Django 4.2.2 on 2023-06-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_citymodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.state'),
        ),
    ]
