# Generated by Django 4.2.2 on 2023-06-17 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_citymodel_state_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='org_name',
        ),
        migrations.AddField(
            model_name='docs',
            name='org_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='home.organizationmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationmodel',
            name='space',
            field=models.IntegerField(default=1048576),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
