# Generated by Django 4.2.2 on 2023-06-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.TextField()),
                ('title', models.TextField()),
                ('header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.header')),
                ('layout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.layout')),
            ],
        ),
    ]
