# Generated by Django 4.2.2 on 2023-06-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contentdata_header_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdata',
            name='unique_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='header',
            name='unique_id',
            field=models.IntegerField(default=0),
        ),
    ]
