from .Token import models
from .login import models
from .Register import models
from .HOD import models
from .Student import models
from .Teacher import models
from .Teacher.subject import models
from .Time_Table import models
from .Grade import models