# Generated by Django 4.2.2 on 2023-06-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organization_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.organization'),
        ),
    ]
