# Generated by Django 4.2.1 on 2023-06-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_delete_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mac',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
