# Generated by Django 4.2.2 on 2023-06-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('log', models.CharField(max_length=15)),
                ('is_credited', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
