# Generated by Django 4.2.2 on 2023-06-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_transaction_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='log',
            new_name='money',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
