# Generated by Django 4.2.2 on 2023-06-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginuser',
            old_name='email',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='username',
        ),
    ]
