# Generated by Django 4.2.2 on 2023-06-10 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_time_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='values',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='standard',
            name='subject_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
