# Generated by Django 4.2.2 on 2023-06-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_subject_name_time_table_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Standard',
            new_name='Subject',
        ),
    ]
