# Generated by Django 4.2.2 on 2023-06-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_time_table_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_table',
            name='day',
            field=models.IntegerField(),
        ),
    ]
