# Generated by Django 4.2.2 on 2023-06-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_time_table_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='standard',
            field=models.IntegerField(default=5),
        ),
    ]
