# Generated by Django 4.2.2 on 2023-06-13 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_customuser_standard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='grade',
            new_name='money',
        ),
    ]
