# Generated by Django 4.2.2 on 2023-06-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher_id',
            field=models.IntegerField(default=0),
        ),
    ]
