# Generated by Django 4.2.1 on 2023-05-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='action',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='trade',
            name='avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='p_l',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
