# Generated by Django 4.2.1 on 2023-05-30 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_trade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Only alphabetic characters are allowed.')]),
        ),
    ]
